from typing import List, Optional, Any, Generic, TypeVar
from pydantic import BaseModel, Field

T = TypeVar("T")

class ApiResponse(BaseModel, Generic[T]):
    success: bool = True
    data: Optional[T] = None
    error: Optional[str] = None

class AnalyzeRequest(BaseModel):
    content: str = Field(..., min_length=3, max_length=15000, description="The message, notice, or document text to analyze")
    language: str = Field(default="en", description="'en' for English or 'hi' for Hindi")
    task_context: Optional[str] = Field(default=None, description="Optional user intent, e.g., 'explain', 'safety_check', 'bill_check'")

class SafetyCheckRequest(BaseModel):
    content: str = Field(..., min_length=3, max_length=15000, description="The message or link to check for safety")
    language: str = Field(default="en", description="'en' or 'hi'")

class ExtractedDate(BaseModel):
    title: str = Field(description="Name of the event or deadline, e.g., 'Electricity Bill Due Date'")
    date_str: str = Field(description="Clear date format, e.g., '25 September 2026'")
    raw_date: Optional[str] = Field(default=None, description="ISO or standard date if parsable, e.g., '2026-09-25'")
    days_remaining: Optional[int] = Field(default=None, description="Estimated days from current date")
    is_urgent: bool = Field(default=False, description="True if due within 5 days")
    action_required: str = Field(description="Action the senior needs to take for this date")

class DifficultWord(BaseModel):
    word: str = Field(description="Technical or bureaucratic term, e.g., 'KYC', 'Disconnection', 'Deductible'")
    simple_meaning: str = Field(description="Very simple explanation for a senior")
    hindi_meaning: Optional[str] = Field(default=None, description="Hindi explanation")

class ActionStep(BaseModel):
    step_number: int
    instruction: str
    caution: Optional[str] = None

class RedFlag(BaseModel):
    flag: str = Field(description="Short title, e.g. 'Urgent Disconnection Threat'")
    why_risky: str = Field(description="Calm, clear explanation of why this is dangerous")
    severity: str = Field(default="medium", description="'low', 'medium', 'high'")

class ProactiveSuggestion(BaseModel):
    title: str = Field(description="Anticipatory alert title, e.g., 'Set a Bill Due Reminder'")
    description: str = Field(description="Gentle suggestion to the senior")
    suggested_action: str = Field(description="'set_reminder', 'verify_helpline', 'ask_caregiver', 'ignore'")
    action_payload: Optional[dict] = Field(default=None, description="Data for one-click action execution")

class AnalysisResponse(BaseModel):
    summary: str = Field(description="1-2 gentle sentences explaining what this document is")
    simple_explanation: str = Field(description="In-depth, jargon-free explanation for a senior citizen")
    hindi_explanation: Optional[str] = Field(default=None, description="Explanation in simple, natural Hindi")
    important_points: List[str] = Field(default_factory=list, description="Top key takeaways")
    dates: List[ExtractedDate] = Field(default_factory=list, description="Extracted deadlines or appointment dates")
    amounts: List[str] = Field(default_factory=list, description="Extracted rupee or monetary amounts")
    actions: List[ActionStep] = Field(default_factory=list, description="Step-by-step checklist of what the senior should do")
    difficult_words: List[DifficultWord] = Field(default_factory=list, description="Glossary of hard words found in text")
    risk_level: str = Field(default="safe", description="'safe', 'caution', 'suspicious', 'high_risk'")
    warnings: List[RedFlag] = Field(default_factory=list, description="Potential warning signs detected")
    safe_next_steps: List[str] = Field(default_factory=list, description="Recommended safe steps")
    proactive_prompt: Optional[ProactiveSuggestion] = Field(default=None, description="Anticipated next action prompt")
    caregiver_summary: str = Field(description="Short summary designed to be forwarded to a son, daughter, or caregiver")
    is_fallback: bool = Field(default=False, description="True if generated by safety fallback engine")
